### ISSUE TITLE
The Select on data.Timezone for $time fails

### ISSUE THREAD

**Issue by Wissididom** [Supinic/supibot#53]
I have just created the table listed under https://github.com/Supinic/supibot/tree/master/commands/time and got the following as an error in `chat_data.Error` then I ran the $time command:
```
SqlError: (conn=4064, no: 1064, SQLState: 42000) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Offset, Name
FROM `data`.`Timezone`
WHERE (Abbreviation = 'australia')
LIMIT 1' at line 1
sql: SELECT Abbreviation, Offset, Name
FROM `data`.`Timezone`
WHERE (Abbreviation = 'australia')
LIMIT 1 - parameters:[]
    at module.exports.createError (/root/supibot/node_modules/mariadb/lib/misc/errors.js:61:10)
    at PacketNodeEncoded.readError (/root/supibot/node_modules/mariadb/lib/io/packet.js:572:19)
    at Query.readResponsePacket (/root/supibot/node_modules/mariadb/lib/cmd/parser.js:55:28)
    at PacketInputStream.receivePacketBasic (/root/supibot/node_modules/mariadb/lib/io/packet-input-stream.js:82:9)
    at PacketInputStream.onData (/root/supibot/node_modules/mariadb/lib/io/packet-input-stream.js:132:20)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:343:12)
    at readableAddChunk (node:internal/streams/readable:316:9)
    at Readable.push (node:internal/streams/readable:253:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

After little playing around with the SQL-Statement in MariaDB I found out that it seems to be the problem, that the `Offset` column name is not quoted.
When I did ``SELECT Abbreviation, `Offset`, `Name` FROM `data`.`Timezone` WHERE (`Abbreviation` = 'australia') LIMIT 1;`` it succeeded with an empty set (as expected), but when I did ``SELECT Abbreviation, Offset, `Name` FROM `data`.`Timezone` WHERE (`Abbreviation` = 'australia') LIMIT 1;`` it failed with the above-mentioned error.

Not sure if that issue is for supibot tho, because I think supi-core handles the whole SQL stuff...

**Comment by Supinic** [comment]
This is odd, as the query works just fine on my version of MariaDB (10.3.38). Can you disclose some info about yours? Columns are not quoted by default when using the `sb.Query` builder, but perhaps this is a good enough reason to consider it.

Although, after looking at this table I'd strongly consider refactoring it into a JSON file - feels much more transparent and easier to use.

**Comment by Wissididom** [comment]
> Can you disclose some info about yours?

mariadb from 11.0.3-MariaDB, client 15.2 for debian-linux-gnu (x86_64) using readline EditLine wrapper

`cat /etc/debian_version` returns `11.7`

The server is running in a Hetzner data center in Nuremberg.

**Comment by Supinic** [comment]
Yep that explains it, `OFFSET` was added as a reserved/keyword with MariaDB `10.6`. 

For this issue though, I'll refactor the time zone table into a JSON as mentioned, and then separately work on quoting columns where necessary - in `supi-core`.
